### ISSUE TITLE
[BUG] 네비게이션 바

### ISSUE THREAD

**Issue by ICESubAcct** [YnexKimdoyeon/Ynex#1]
<img width="592" alt="image" src="https://github.com/YnexKimdoyeon/Ynex/assets/153160638/0988fcbe-9498-48af-b441-220aa686d002">

네비게이션에서 메뉴를 눌렀을 때 해당 메뉴의 색이 파란색으로 변하지 않습니다.

**Comment by JungSeungJi** [comment]
clear.
